spring.application.name=Veterinaria

spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# Credenciales de acceso a MySQL
spring.datasource.username=root
spring.datasource.password=

# Driver de MySQL (opcional en versiones recientes, pero recomendado)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# create-drop: borra y crea las tablas cada vez que inicia la app (ideal para desarrollo)
# update: actualiza las tablas sin borrar datos existentes
# validate: solo valida que coincidan
spring.jpa.hibernate.ddl-auto=update

# Dialecto de la base de datos (opcional, Hibernate lo detecta solo por el driver)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mostrar las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
